Main svc
KirillSenchenkov/java-explore-with-me pull request #4
Opened 2023-10-18 20:31 UTC by KirillSenchenkov

2023-10-19 18:00 UTC, sergeymamonov requested changes
Лучше когда применяются одинаковые решения для схожих участков кода. Сейчас где-то для классов dto используется модификатор final, где-то аннотация @FieldDefaults. Лучше сделать однообразно.

Лучше вместо @Data использовать только нужные аннотации.

2023-10-21 20:20 UTC, sergeymamonov approved these changes
Разберитесь **со всеми** классами dto чтобы эти классы были неизменяемыми.

2023-10-21 20:20 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/event/EventService.java
> +        if (eventTime.isBefore(ACTUAL_TIME.plusHours(2))) {
Не исправлено. Числа лучше вынести в константы с информативным названием.

2023-10-21 20:36 UTC, KirillSenchenkov commented on main-service/src/main/java/ru/practicum/ewm/event/EventService.java
> +        if (eventTime.isBefore(ACTUAL_TIME.plusHours(2))) {
Я тогда не понимаю в чем заключается задача ? Мы говорим не про константу для localdatetime.now?

2023-10-22 09:07 UTC, merged